apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "solr-standalone.fullname" . }}
  labels:
    {{- include "solr-standalone.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "solr-standalone.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "solr-standalone.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      volumes:
        - name: data
          hostPath:
            path: "/data/glusterfs/solr"
            type: DirectoryOrCreate
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- if .Values.solr.cores }}
          command:
            - /bin/bash
            - -c
          args:
            - |
              mkdir -p /var/solr/data && \
              {{- $cores := .Values.solr.cores }}
              {{- $cmd := "" }}
              {{- range $index, $core := $cores }}
                {{- if gt $index 0 }}
                  {{- $cmd = printf "%s && precreate-core %s" $cmd $core }}
                {{- else }}
                  {{- $cmd = printf "precreate-core %s" $core }}
                {{- end }}
              {{- end }}
              {{- $cmd = printf "%s && exec solr -f" $cmd }}
              {{ $cmd }}
          {{- end }}
          #volumeMounts:
          #  - mountPath: "/var/solr"
          #    name: data
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /solr
              port: http
            initialDelaySeconds: 15
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: /solr
              port: http
            initialDelaySeconds: 15
            timeoutSeconds: 5
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
