apiVersion: v1
kind: Service
metadata:
  name: {{ include "solr-standalone.fullname" . }}
  labels:
    {{- include "solr-standalone.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
      name: http
  selector:
    {{- include "solr-standalone.selectorLabels" . | nindent 4 }}
